---
env:
  browser: true
  node: true
extends:
  - eslint-config-airbnb-base
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
overrides:
  - env:
      mocha: true
    files:
      - '**/*.test.ts'
      - '**/*.spec.ts'
      - '**/*-spec.ts'
      - test/**/*
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2019
  sourceType: module
plugins:
  - eslint-plugin-tsdoc
  - prettier
rules:
  '@typescript-eslint/no-var-requires': 'off'
  import/extensions:
    - error
    - .ts: ignorePackages
  import/no-extraneous-dependencies: 'off'
  import/prefer-default-export: 'off'
  linebreak-style: 'off'
  max-classes-per-file: 'off'
  no-confusing-arrow: 'off'
  no-multiple-empty-lines: error
  no-unused-vars:
    - warn
    - argsIgnorePattern: ^_
  prettier/prettier: error
  quotes:
    - error
    - single
  semi:
    - error
    - always
  sort-imports:
    - error
    - ignoreDeclarationSort: true
  tsdoc/syntax: warn
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .ts
