RetryDefault:
  Retry: &ref_0
    - BackoffRate: 2
      ErrorEquals:
        - States.ALL
      IntervalSeconds: 2
      MaxAttempts: 1
custom:
  integrationName: '${self:service}-${self:provider.stage}'
  test:
    pagerDutyArn: arn:aws:sns:us-west-2:244249143763:pager_duty
  prod:
    pagerDutyArn: arn:aws:sns:us-west-2:529464811624:ns8_alerts
  alerts:
    stages:
      - test
      - prod
    dashboards: true
    nameTemplate: $[functionName]-$[metricName]-Alarm
    prefixTemplate: $[stackName]
    properties:
      alarmActions:
        - ${self:custom.${self:provider.stage}.pagerDutyArn}
      alarmDescription: |
        Error Alarm for Polling Lambda Functions
    definitions:
      functionErrors:
        namespace: 'AWS/Lambda'
        threshold: 1
        statistic: Sum
        period: 300
        evaluationPeriods: 1
        datapointsToAlarm: 1
        comparisonOperator: GreaterThanThreshold
      functionDuration:
        namespace: 'AWS/Lambda'
        metric: Duration
        threshold: 2500
        statistic: Maximum
        period: 60
        evaluationPeriods: 1
        comparisonOperator: GreaterThanOrEqualToThreshold
        treatMissingData: missing
    alarms:
      - functionErrors
      - functionDuration
  commonResourceStage: ${self:custom.commonResourceStageLookup.${self:provider.stage}, "dev-all"}
  commonResourceStageLookup:
    #dev-<name>: dev-all
    test: test
    prod: prod
functions:
  CreatePolledMessage:
    environment:
      STAGE: '${self:provider.stage}'
    handler: dist/index.createPolledMessage
    name: '${self:custom.integrationName}-createPolledMessage'
  DeletePolledMessage:
    environment:
      STAGE: '${self:provider.stage}'
    handler: dist/index.deletePolledMessage
    name: '${self:custom.integrationName}-deletePolledMessage'
  GetPollUrl:
    environment:
      STAGE: '${self:provider.stage}'
    handler: dist/index.getPollUrl
    name: '${self:custom.integrationName}-getPollUrl'
package:
  exclude:
    - ./**
  include:
    - dist/index.js
    - serverless.yml
plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters
  - serverless-plugin-aws-alerts
provider:
  deploymentBucket:
    name: '${ssm:/serverless/deployment/bucket/name}'
  name: aws
  region: us-west-2
  role: arn:aws:iam::#{AWS::AccountId}:role/protect-switchboard-sdk-${self:custom.commonResourceStage}-lambdaRole
  runtime: nodejs12.x
  stage: '${opt:stage}'
  timeout: 29
  versionFunctions: false
  stackTags:
    'ns8.configured-by': protect-sdk-switchboard
    'ns8.usecase': protect-sdk-switchboard
    'ns8.stage': ${self:provider.stage}

service: protect-switchboard-sdk

