/**
 * Order data mocks for automated testing
 * @public
 */
export const orderMocks = [
  {
    addresses: [
      {
        address1: 'd',
        address2: 'd',
        city: 'd',
        company: null,
        country: 'Belarus',
        countryCode: 'BY',
        latitude: null,
        longitude: null,
        name: 'd d',
        region: null,
        regionCode: null,
        type: 'BILLING',
        zip: 'd',
      },
      {
        address1: 'd',
        address2: 'd',
        city: 'd',
        company: null,
        country: 'Belarus',
        countryCode: 'BY',
        latitude: null,
        longitude: null,
        name: 'd d',
        region: null,
        regionCode: null,
        type: 'SHIPPING',
        zip: 'd',
      },
    ],
    createdAt: 1586864886339,
    currency: 'USD',
    customer: {
      birthday: null,
      company: null,
      email: 'rasmus.lisborg@e2ycommerce.com',
      firstName: 'd',
      gender: null,
      isEmailVerified: null,
      isPayingCustomer: null,
      lastName: 'd',
      phone: 'd',
      platformCreatedAt: 1586864839583,
      platformId: '559e10a2-777d-4630-be6c-cabd0635753d|rasmus.lisborg@e2ycommerce.com',
      totalSpent: null,
    },
    hasGiftCard: null,
    lineItems: [
      {
        ean13: '8714574533421',
        isbn: null,
        isGiftCard: null,
        manufacturer: 'Canon',
        name: 'PowerShot A480',
        platformId: '00000001-0',
        platformProductId: '1934793',
        price: 99.85,
        quantity: 1,
        sku: '3477B013AA',
        title:
          '<b>Affordable, intuitive and fun, the PowerShot A480 uses Canon know-how to let everyone take great 10 MP photos. Available in four colours, its compact, lightweight design slips easily into any pocket.</b><br/><br/><b>10.0 Megapixels</b><br/>With a 10 Megapixel sensor, you can capture every scene in vivid detail – ready for printing at sizes as large as A3+, or cropping to perfection without losing the detail necessary for larger prints.<br/><br/><b>Compact and colourful</b><br/>Small and light enough to slip into a pocket, the PowerShot A480 has a classic, stylish design that feels great in the hand. Controlled by a simple button layout, it comes in a choice of four attractive colours.<br/><br/><b>3.3x optical zoom</b><br/>Frame every picture perfectly with a Canon 3.3x optical zoom. In combination with digital zoom, magnification of up to 13x can be achieved.<br/><br/><b>DIGIC III</b><br/>As well as powering Face Detection Technology, Canon’s DIGIC III processor provides fast response times, superb image quality and colour reproduction. DIGIC III also delivers advanced noise reduction – ensuring that images remain sharp and clear.<br/><br/><b>15 shooting modes</b><br/>A selection of shooting modes - including dedicated Kids & Pets and Indoor modes - make it easy to get the right settings for any scene. Simply select the mode you want, and let the camera take care of everything else. <br/><br/><b>1cm Macro shooting</b><br/>A special 1cm Super Macro mode allows you to capture small scale detail from as close as 1cm away.<br/><br/><b>Great people shots</b><br/>A suite of Face Detection technologies detects up to nine faces in a scene and adjusts focus, exposure, flash settings and white balance – for optimal results with natural-looking skin tones. <br/><br/><b>Auto Red-Eye Correction</b><br/>Available in shooting or playback mode, Automatic Red-Eye Correction accurately removes the red-eye effect caused by flash. <br/><br/><b>Motion Detection Technology</b><br/>Motion Detection Technology uses changes in scene information and scene brightness to accurately identify subject motion. The optimal ISO level is then automatically set, to minimise blur and maximise image quality.',
        totalDiscount: 0,
        upc: null,
        variantId: null,
        variantTitle: null,
        vendor: null,
      },
    ],
    merchantId: '2be74ea0-b589-4a37-ab6a-6bc34b01eb3f',
    name: 'foo',
    platformCreatedAt: 1586864886339,
    platformId: 'cristiancantcatchme',
    platformStatus: null,
    session: {
      acceptLanguage: null,
      ip: '127.0.0.1',
      screenHeight: null,
      screenWidth: null,
      userAgent:
        'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36',
    },
    status: null,
    totalPrice: 108.84,
    transactions: [
      {
        amount: 108.84,
        creditCard: {
          avsResultCode: null,
          cardExpiration: '4/2024',
          cardHolder: 'd d',
          creditCardBin: null,
          creditCardCompany: 'VISA',
          creditCardNumber: '************1111',
          cvvResultCode: null,
          gateway: null,
          transactionType: 'AUTHORIZATION',
        },
        currency: 'USD',
        method: 'CC',
        platformId: '123456789',
        processedAt: 1586864886263,
        status: 'SUCCESS',
        statusDetails: 'SUCCESFULL',
      },
    ],
    updatedAt: 1586864890783,
  },
];
