executors:
  nodeaws-executor:
    docker:
      - image: ns8inc/nodeaws:node-erbium
orbs:
  assume-role: airswap/assume-role@0.2.0
jobs:
  deploy_test_and_dev:
    executor: nodeaws-executor
    steps:
      - add_ssh_keys:
          fingerprints:
            - "9f:0b:68:b4:5b:ce:aa:60:94:0a:a5:66:43:7a:3a:df"
      - checkout
      - run:
          command: echo "//registry.npmjs.org/:_authToken=${NS8_GLOBAL_NPM_TOKEN}" > ~/.npmrc
          name: Configure NPM
      - run:
          command: yarn
          name: Install Dependencies
      - run:
          command: yarn build:prod
          name: Build for Production
      - run:
          command: yarn deploy --stage=dev
          name: Deploy Switchboard (dev)
      - run:
          command: yarn deploy --stage=test
          name: Deploy Switchboard (test)
  deploy_prod:
    executor: nodeaws-executor
    steps:
      - add_ssh_keys:
          fingerprints:
            - "9f:0b:68:b4:5b:ce:aa:60:94:0a:a5:66:43:7a:3a:df"
      - checkout
      - run:
          command: |
            git config user.email noreply@ns8.com
            git config user.name 'CircleCI'
          name: Setup Git
      - run:
          command: |
            yarn config set version-tag-prefix ''
            yarn version --patch
          name: Bump Version
      - run:
          command: |
            if ! git push -u origin master --follow-tags; then
              echo "Push failed. Please add this CircleCI deploy key to your repo with write access:"
              ssh-keygen -y -f ~/.ssh/id_rsa
              exit 1
            fi
          name: Tag Release in GitHub
      - run:
          command: echo "//registry.npmjs.org/:_authToken=${NS8_GLOBAL_NPM_TOKEN}" > ~/.npmrc
          name: Configure NPM
      - run:
          command: yarn
          name: Install Dependencies
      - run:
          command: yarn build:prod
          name: Build for Production
      - run:
          command: yarn docs:publish
          name: Publish API docs to Github Pages
      - run:
          command: npm publish
          name: Publish
      - assume-role/assume-role:
          account-id: "529464811624"
          role-name: circle-ci-role
      - run:
          command: yarn deploy --stage=prod
          name: Deploy Switchboard (prod)
  test:
    executor: nodeaws-executor
    steps:
      - checkout
      - run:
          command: |
            set +eo pipefail
            if git log | head -n 2 | tail -n 1 | grep 'Author: CircleCI'; then
              circleci step halt
            fi
          name: Skip if CI Made the Last Commit
      - run:
          command: echo "//registry.npmjs.org/:_authToken=${NS8_GLOBAL_NPM_TOKEN}" > ~/.npmrc
          name: Configure NPM
      - run:
          command: yarn
          name: Install Dependencies
      - run:
          command: yarn lint
          name: Lint
      - run:
          command: yarn test:coverage
          name: Run Tests
version: 2.1
workflows:
  test_and_deploy:
    jobs:
      - test:
          context: org-global
      - deploy_test_and_dev:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              only: master
              ignore: /.*/
          requires:
            - test
          context: org-global
      - approve:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - test
          context: org-global
      - deploy_prod:
          requires:
            - approve
