executors:
  nodeaws-executor:
    docker:
      - image: luddites-me/nodeaws:node-erbium
jobs:
  deploy_test_and_dev:
    executor: nodeaws-executor
    steps:
      - checkout
      - run:
          command: echo "//registry.npmjs.org/:_authToken=${LUDDITES_GLOBAL_NPM_TOKEN}" > ~/.npmrc
          name: Configure NPM
      - run:
          command: yarn
          name: Install Dependencies
      - run:
          command: yarn build:prod
          name: Build for Production
      - run:
          command: yarn deploy --stage=dev
          name: Deploy Switchboard (dev)
      - run:
          command: yarn deploy --stage=test
          name: Deploy Switchboard (test)
  prep_release:
    executor: nodeaws-executor
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "77:0b:17:b2:eb:5a:1d:4f:39:df:d1:ef:2f:a5:69:34"
      - run:
          command: echo "//registry.npmjs.org/:_authToken=${LUDDITES_GLOBAL_NPM_TOKEN}" > ~/.npmrc
          name: Configure NPM
      - run:
          command: yarn
          name: Install Dependencies
      - run:
          command: yarn build:prod
          name: Build for Production
      - run:
          command: |
            git config user.email noreply@luddites-me.com
            git config user.name 'CircleCI'
          name: Setup Git
      - run:
          command: |
            yarn config set version-tag-prefix ''
            current_version="$(jq -r .version package.json)"

            while
              new_version="$(jq -r .version package.json)"
              [[ "$(git tag | grep -c $new_version)" -gt "0" ]]
            do yarn version --no-git-tag-version --patch; done
            if [ "$new_version" = "$current_version" ]; then
              # Someone manually bumped the version in package.json, so don't bump, only tag.
              git tag $new_version
            else
              # Reset then bump and tag like usual.
              git checkout package.json
              yarn version --new-version $new_version
            fi
          name: Bump Version
      - run:
          command: |
            if ! git push -u origin master --tags; then
              echo "Push failed. Please add this CircleCI deploy key to your repo with write access:"
              ssh-keygen -y -f ~/.ssh/id_rsa
              exit 1
            fi
          name: Tag Release in GitHub
      - run:
          command: yarn docs:publish
          name: Publish API docs to Github Pages
      - run:
          command: npm publish
          name: Publish
  deploy_prod:
    executor: nodeaws-executor
    steps:
      - checkout
      - run:
          command: echo "//registry.npmjs.org/:_authToken=${LUDDITES_GLOBAL_NPM_TOKEN}" > ~/.npmrc
          name: Configure NPM
      - run:
          command: yarn
          name: Install Dependencies
      - run:
          command: yarn build:prod
          name: Build for Production
      - assume-role/assume-role:
          account-id: "529464811624"
          role-name: circle-ci-role
      - run:
          command: yarn deploy --stage=prod
          name: Deploy Switchboard (prod)
  publish:
    executor: nodeaws-executor
    steps:
      - checkout
      - run:
          command: echo "//registry.npmjs.org/:_authToken=${LUDDITES_GLOBAL_NPM_TOKEN}" > ~/.npmrc
          name: Configure NPM
      - run:
          command: yarn
          name: Install Dependencies
      - run:
          command: |
            version=$(jq -r .version package.json)
            echo "export VERSION=$version" >> $BASH_ENV
          name: Get Version
      - run:
          command: |
            yarn gren release -m -t $VERSION -T $GITHUB_ACCESS_TOKEN
            yarn gren release -o -t $VERSION -T $GITHUB_ACCESS_TOKEN
          name: Create GitHub Release
  test:
    executor: nodeaws-executor
    steps:
      - checkout
      - run:
          command: |
            set +eo pipefail
            if git log | head -n 2 | tail -n 1 | grep 'Author: CircleCI'; then
              circleci step halt
            fi
          name: Skip if CI Made the Last Commit
      - run:
          command: echo "//registry.npmjs.org/:_authToken=${LUDDITES_GLOBAL_NPM_TOKEN}" > ~/.npmrc
          name: Configure NPM
      - run:
          command: yarn
          name: Install Dependencies
      - run:
          command: yarn lint
          name: Lint
      - run:
          command: yarn test:coverage
          name: Run Tests
orbs:
  assume-role: airswap/assume-role@0.2.0
version: 2.1
workflows:
  publish:
    jobs:
      - approve:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
          type: approval
      - publish:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
          requires:
            - approve
  test_and_deploy:
    jobs:
      - test:
          context: org-global
      - deploy_test_and_dev:
          context: org-global
          filters:
            branches:
              only: master
          requires:
            - test
      - approve_prep_release:
          context: org-global
          filters:
            branches:
              only: master
          requires:
            - deploy_test_and_dev
          type: approval
      - prep_release:
          context: org-global
          filters:
            branches:
              only: master
          requires:
            - approve_prep_release
      - approve_deploy_prod:
          context: org-global
          filters:
            branches:
              only: master
          requires:
            - test
          type: approval
      - deploy_prod:
          context: org-global
          requires:
            - approve_deploy_prod
