export enum OrderEventType {
  CREATED = 'CREATED',
  UPDATED_STATUS = 'UPDATED_STATUS',
  UPDATED_RISK = 'UPDATED_RISK',
  LUDDITES_FRAUD_ASSESSMENT_ADDED = 'LUDDITES_FRAUD_ASSESSMENT_ADDED',
  LUDDITES_FRAUD_RULES_COMPLETE = 'LUDDITES_FRAUD_RULES_COMPLETE',
  WPP_FRAUD_ASSESSMENT_ADDED = 'WPP_FRAUD_ASSESSMENT_ADDED',
  CUSTOMER_VERIFICATION_CREATED = 'CUSTOMER_VERIFICATION_CREATED',
  CUSTOMER_VERIFICATION_UPDATED = 'CUSTOMER_VERIFICATION_UPDATED',
  CUST_VERIFY_RULES_COMPLETE = 'CUST_VERIFY_RULES_COMPLETE',
}
