export enum SwitchEventType {
    ON_ENABLE_EXTENSION = 'ON_ENABLE_EXTENSION_EVENT',
    ON_UPDATE_EXTENSION_MERCHANT = 'ON_UPDATE_EXTENSION_MERCHANT_EVENT',
    ON_UPDATE_EXTENSION_ORDER = 'ON_UPDATE_EXTENSION_ORDER_EVENT',
    ON_UPDATE_EXTENSION_ORDER_RISK = 'ON_UPDATE_EXTENSION_ORDER_RISK_EVENT',
    ON_DISABLE_EXTENSION = 'ON_DISABLE_EXTENSION_EVENT',
    ON_INSTALL_PLATFORM = 'ON_INSTALL_PLATFORM_EVENT',
    UPDATE_CUSTOMER_VERIFICATION_STATUS = 'UPDATE_CUSTOMER_VERIFICATION_STATUS_EVENT',
    UPDATE_EQ8_SCORE = 'UPDATE_EQ8_SCORE_EVENT',
    UPDATE_ORDER_RISK = 'UPDATE_ORDER_RISK_EVENT',
    UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS_EVENT',
}
