export enum SwitchActionType {
    CREATE_ORDER = 'CREATE_ORDER_ACTION',
    UNINSTALL = 'UNINSTALL_ACTION',
    UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS_ACTION',
    UPDATE_MERCHANT = 'UPDATE_MERCHANT_ACTION',
    WEBHOOK = 'WEBHOOK_ACTION',
}
