export enum OrderRuleAction {
  'SET_RISK_HIGH' = 'SET_RISK_HIGH',
  'SET_RISK_MEDIUM' = 'SET_RISK_MEDIUM',
  'SET_RISK_LOW' = 'SET_RISK_LOW',
  'VERIFY_CUSTOMER' = 'VERIFY_CUSTOMER',
  'CANCEL' = 'CANCEL',
  'APPROVE' = 'APPROVE',
  'EXECUTE_WPP' = 'EXECUTE_WPP',
  'NO_ACTION' = 'NO_ACTION',
}
